/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-06 05:49:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import persistence.Inspect;

public final class viewInspect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1673798774412L));
    _jspx_dependants.put("jar:file:/D:/pbl3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/laptrinhdoan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673791737465L));
    _jspx_dependants.put("jar:file:/D:/pbl3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/laptrinhdoan/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1671200051085L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("persistence.Inspect");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Trang chủ</title>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".get-in-touch {\r\n");
      out.write("  max-width: 800px;\r\n");
      out.write("  margin: 50px auto;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  background-image: url(https://img.lovepik.com/free-png/20211225/lovepik-security-inspectors-png-image_400381051_wh860.png);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".get-in-touch .title {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  letter-spacing: 3px;\r\n");
      out.write("  font-size: 3.2em;\r\n");
      out.write("  line-height: 48px;\r\n");
      out.write("  padding-bottom: 48px;\r\n");
      out.write("     color: #5543ca;\r\n");
      out.write("    background: #5543ca;\r\n");
      out.write("    background: -moz-linear-gradient(left,#f4524d  0%,#5543ca 100%) !important;\r\n");
      out.write("    background: -webkit-linear-gradient(left,#f4524d  0%,#5543ca 100%) !important;\r\n");
      out.write("    background: linear-gradient(to right,#f4524d  0%,#5543ca  100%) !important;\r\n");
      out.write("    -webkit-background-clip: text !important;\r\n");
      out.write("    -webkit-text-fill-color: transparent !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form .form-field {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin: 32px 0;\r\n");
      out.write("}\r\n");
      out.write(".contact-form .input-text {\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 36px;\r\n");
      out.write("  border-width: 0 0 2px 0;\r\n");
      out.write("  border-color: #5543ca;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  line-height: 26px;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("}\r\n");
      out.write(".contact-form .input-text:focus {\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write(".contact-form .input-text:focus + .label,\r\n");
      out.write(".contact-form .input-text.not-empty + .label {\r\n");
      out.write("  -webkit-transform: translateY(-24px);\r\n");
      out.write("          transform: translateY(-24px);\r\n");
      out.write("}\r\n");
      out.write(".contact-form .label {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 20px;\r\n");
      out.write("  bottom: 11px;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  line-height: 26px;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  color: #5543ca;\r\n");
      out.write("  cursor: text;\r\n");
      out.write("  transition: -webkit-transform .2s ease-in-out;\r\n");
      out.write("  transition: transform .2s ease-in-out;\r\n");
      out.write("  transition: transform .2s ease-in-out, \r\n");
      out.write("  -webkit-transform .2s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".contact-form .submit-btn {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  background-color: #000;\r\n");
      out.write("   background-image: linear-gradient(125deg,#a72879,#064497);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  letter-spacing: 2px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  padding: 8px 16px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  width:200px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!--important link source from \"https://bootsnipp.com/snippets/A36DP\"-->\r\n");
      out.write("\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
Inspect inspect = (Inspect)request.getAttribute("inspect"); 
      out.write("\r\n");
      out.write("<section class=\"get-in-touch\">\r\n");
      out.write("\r\n");
      out.write("   <h1 class=\"title\">Chỉnh Sửa Thông Tin Thanh Tra </h1>\r\n");
      out.write("   <form class=\"contact-form row\"  action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"  method=\"get\">\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("      <div class=\"form-field col-lg-6 \">\r\n");
      out.write("      <label >Tên</label>\r\n");
      out.write("         <input id=\"company\" class=\"input-text js-input\" type=\"text\" required name=\"name\" value=\"");
      out.print(inspect.getName());
      out.write("\">\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"form-field col-lg-6 \">\r\n");
      out.write("       <label >Số điện thoại</label>\r\n");
      out.write("         <input id=\"phone\" class=\"input-text js-input\" type=\"text\" required name=\"phone\" value=\"");
      out.print(inspect.getPhone() );
      out.write("\">\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-field col-lg-12\">\r\n");
      out.write("      <label >Địa chỉ</label>\r\n");
      out.write("         <input id=\"message\" class=\"input-text js-input\" type=\"text\" required name=\"address\" value=\"");
      out.print(inspect.getAddress() );
      out.write("\">\r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("         <input id=\"company\" class=\"input-text js-input\" type=\"hidden\" required name=\"inspectId\" value=\"");
      out.print(inspect.getId() );
      out.write("\">\r\n");
      out.write("         <input id=\"company\" class=\"input-text js-input\" type=\"hidden\" required name=\"action\" value=\"update\">\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("       <div class=\"form-field col-lg-6\">\r\n");
      out.write("         <input class=\"submit-btn\" type=\"submit\" value=\"register\">\r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"form-field col-lg-6\">\r\n");
      out.write("         <input class=\"submit-btn\" type=\"reset\" value=\"reset\">\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("   </form>\r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/admin/viewInspect.jsp(96,43) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/admin-update?action=update");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
